version: '3.9'
services:
  APP_NAME:
    container_name: APP_NAME
    image: 'registry.richardxiong.com/APP_NAME:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.APP_NAME.rule=Host(`APP_NAME.richardxiong.com`)
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET

networks:
  default:
    name: proxy
    external: true
