version: '3.9'
services:
  zoom:
    container_name: zoom
    image: 'registry.richardxiong.com/zoom:latest'
    restart: unless-stopped
    ports:
      - '3005'
    labels:
      - traefik.enable=true
      - traefik.http.routers.zoom.rule=Host(`zoom.richardxiong.com`)
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY

networks:
  default:
    name: proxy
    external: true
